apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Application Release with manifest
on:
  workflow_dispatch:
    inputs:
      manifest:
        type: string
        required: true
jobs:
  pre-prod:
    environment: pre-prod
    steps:
      - name: Deploy App8-Frontend to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App8-Frontend']['App8-Frontend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App8-Frontend']['App8-Frontend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App8-Frontend']['App8-Frontend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App8-Frontend']['App8-Frontend'].digest }}
          target-environment: pre-prod
          name: App8-Frontend

      - name: Deploy App8-Backend to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App8-Backend']['App8-Backend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App8-Backend']['App8-Backend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App8-Backend']['App8-Backend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App8-Backend']['App8-Backend'].digest }}
          target-environment: pre-prod
          name: App8-Backend

      - name: Deploy App8-APIs to Preprod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App8-APIs']['App8-APIs'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App8-APIs']['App8-APIs'].version }}
          url: ${{ fromJSON(inputs.manifest)['App8-APIs']['App8-APIs'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App8-APIs']['App8-APIs'].digest }}
          target-environment: pre-prod
          name: App8-APIs
  prod:
    needs: pre-prod
    environment: prod
    steps:
      - name: Deploy App8-Frontend to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App8-Frontend']['App8-Frontend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App8-Frontend']['App8-Frontend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App8-Frontend']['App8-Frontend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App8-Frontend']['App8-Frontend'].digest }}
          target-environment: prod
          name: App8-Frontend

      - name: Deploy App8-Backend to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App8-Backend']['App8-Backend'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App8-Backend']['App8-Backend'].version }}
          url: ${{ fromJSON(inputs.manifest)['App8-Backend']['App8-Backend'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App8-Backend']['App8-Backend'].digest }}
          target-environment: prod
          name: App8-Backend

      - name: Deploy App8-APIs to Prod
        kind: deploy
        if: ${{ fromJSON(inputs.manifest)['App8-APIs']['App8-APIs'].deploy }}
        uses: cloudbees-io/register-deployed-artifact@v1
        with:
          version: ${{ fromJSON(inputs.manifest)['App8-APIs']['App8-APIs'].version }}
          url: ${{ fromJSON(inputs.manifest)['App8-APIs']['App8-APIs'].url }}
          digest: ${{ fromJSON(inputs.manifest)['App8-APIs']['App8-APIs'].digest }}
          target-environment: prod
          name: App8-APIs
